name: logos
on: [push, pull_request]

jobs:
  realm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: logos
        run: |
          go mod download github.com/davecgh/go-spew
          go mod download
          cd logos/cmd
          go build .
          ls -a
          go run logos.go
