name: test realm
on: [push, pull_request]

jobs:
  realm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: test realms
        run: |
          go mod download github.com/davecgh/go-spew
          go test tests/*.go -v -run="Test/realm.go"
          
